### ISSUE TITLE
This plugin is no compatible with this version of openCPN

### ISSUE THREAD

**Issue by pavelpasha** [nohal/launcher_pi#4]
I builded install package and install it. But the error, that mentioned in the title  appears.
OpenCPN 4.4.0
wxWidget3.1.0
VC 14

**Comment by rgleason** [comment]
we are using wxWidgets 3.0.2 and VStudio 13 don't know if that is the problem.

**Comment by nohal** [comment]
You can not mix the official OpenCPN 4.4.0, built with completely different, ABI incompatible, wxWidgets version and a different MSVC runtime with your plugin builds and expect it to work.
If you build everything yourself, it should work. If it doesn't, I gladly accept patches to fix it. I am not going to switch my own systems to use either VC14 or wx3.1 in any near future, sorry.

**Comment by rgleason** [comment]
I just was able to git clone  https://github.com/nohal/launcher_pi  to source\plugins
Copy source\plugins\launcher_pi\data\*.* to source\build\plugins\launcher_pi\data
Then at source\build cmake -T v120_xp ..  and then cmake --build .  then copy the debug version to the build\plgin\lancher_pi directory.  Then start MS VStudio2013 and build again after loading.  Then Debug>Start Debug and I found that launcher_pi was available and works except can't enter the command because the box won't stretch.  This was a problem since before. 

So the plgin works!  Except needs a little tweak.
